In [1]:
import numpy as np

In [219]:
class sudoku_board :
    
    def __init__(self, board):
        """
        transform a list into a board game
        """
        assert np.shape(board) == (9,9)
        self.grid = np.array(board)
       
    def display(self):
        print(self.grid)
                    
    def find_empty_location(self,l): 
        """
        stopping condition in the recursive function
        """
        for row in range(9): 
            for col in range(9): 
                if(self.grid[row][col]==0): 
                    l[0]=row 
                    l[1]=col 
                    return True
        return False  
        
    def submatrix(self, i, j):
        """
        return the square where the point with coordinate i,j is located
        """
        first = i // 3
        second = j // 3
        return self.grid[3*first:3*first+3, 3*second:3*second+3]
        
    def row(self,i,j):
        """
        return the row where the point with coordinate i,j is located
        """
        self.grid
        return self.grid[i,:]
        
    def column(self,i,j):
        """
        return the column where the point with coordinate i,j is located
        """
        return self.grid[:,j]
    
    def safe_location(self, k, i, j):
        """
        checks if k can be placed at the position i,j 
        """
        if not((k in self.column(i,j)) or (k in self.submatrix(i,j)) or (k in self.row(i,j))):
            return True
        else:
            return False
            
    def solve_sudoku(self): 
        """
        return True if the sudoku is solved and False if it can not be solved
        """
      
        # 'l' is a list variable that keeps the record of row and col in find_empty_location Function     
        l=[0,0] 

        # If there is no more 0 in the grid, the sudoku has been solved 
        #the call to the function updates l with the next 0 
        if(not self.find_empty_location(l)): 
            return True

        # Assigning list values to row and col that we got from the above Function  
        row=l[0] 
        col=l[1] 

        # here we test every digit
        for k in range(1,10): 
            
            # if k can be places here
            if(self.safe_location(k,row,col)): 
                
                # we test with k 
                self.grid[row,col] = k 
                
                # recursive call  
                if(self.solve_sudoku()): 
                    return True
                
                # means it failed wo we try again
                self.grid[row,col] = 0
        
        # this triggers backtracking         
        return False 

In [223]:
grid=[[3,0,6,5,0,8,4,0,0], 
          [5,2,0,0,0,0,0,0,0], 
          [0,8,7,0,0,0,0,3,1], 
          [0,0,3,0,1,0,0,8,0], 
          [9,0,0,8,6,3,0,0,5], 
          [0,5,0,0,9,0,6,0,0], 
          [1,3,0,0,0,0,2,5,0], 
          [0,0,0,0,0,0,0,7,4], 
          [0,0,5,2,0,6,3,0,0]] 

board = sudoku_board(grid) #create the object sudoku_board
board.solve_sudoku() #solve the puzzle
board.display() #print the result

[[3 1 6 5 7 8 4 9 2]
 [5 2 9 1 3 4 7 6 8]
 [4 8 7 6 2 9 5 3 1]
 [2 6 3 4 1 5 9 8 7]
 [9 7 4 8 6 3 1 2 5]
 [8 5 1 7 9 2 6 4 3]
 [1 3 8 9 4 7 2 5 6]
 [6 9 2 3 5 1 8 7 4]
 [7 4 5 2 8 6 3 1 9]]
